GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs?search=H

###

POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
  "author": "Gill Bates",
  "url": "microsoft.com",
  "title": "My new os",
  "likes": 2
}

###

POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RndXlAbWljcm9zb2Z0LmNvbSIsImlkIjoxLCJpYXQiOjE2ODEwNDYyMjd9.xOB8TX3bftjYotVvcwGz2oFf3BdKHBiZmGzqIldu1ew

{
  "author": "Alf",
  "url": "myspace.com/alf",
  "title": "MY BLOG 2",
  "year": 2023
}

###

DELETE http://localhost:3001/api/blogs/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RndXlAbWljcm9zb2Z0LmNvbSIsImlkIjoxLCJpYXQiOjE2ODEwNDQ5MDV9.3LnHqk6be8rkgj4Uhm61rITbLYdpdQNkh_fs-KkNC6U

###

PUT http://localhost:3001/api/blogs/5 HTTP/1.1
Content-Type: application/json

{
  "likes": 77
}

### users

GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "testguy@microsoft.com",
  "name": "Test Guy"
}

###

PUT http://localhost:3001/api/users/testguy@microsoft.de HTTP/1.1
Content-Type: application/json

{
  "username": "testguy@microsoft.com"
}

### login

POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "testguy@microsoft.com",
  "password": "secret"
}

###

GET http://localhost:3001/api/authors
