GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
  "author": "Gill Bates",
  "url": "microsoft.com",
  "title": "My new os",
  "likes": 2
}

###

POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
  "author": "Henri Hamunen",
  "url": "myspace.com/hackerman",
  "title": "Whats up guys",
  "likes": 4
}

###

DELETE http://localhost:3001/api/blogs/6 HTTP/1.1

###

PUT http://localhost:3001/api/blogs/1 HTTP/1.1
Content-Type: application/json

{
  "alikes": 77
}

### users

GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "testguy",
  "name": "Test Guy"
}

###

PUT http://localhost:3001/api/users/testguy HTTP/1.1
Content-Type: application/json

{
  "username": "tester"
}
