GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs?search=H

###

POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im90aGVyQG1pY3Jvc29mdC5jb20iLCJpZCI6MiwiaWF0IjoxNjgxMDQ5MjkyfQ.cEt05osNCF7UW1zr7xbRyoV4INVjaYWA-v0itetZ4Ho

{
  "author": "Gill Bates",
  "url": "microsoft.com",
  "title": "Still blogging in 2000",
  "year": 2000,
  "likes": 420
}

###

POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RndXlAbWljcm9zb2Z0LmNvbSIsImlkIjoxLCJpYXQiOjE2ODEwNDYyMjd9.xOB8TX3bftjYotVvcwGz2oFf3BdKHBiZmGzqIldu1ew

{
  "author": "Random guy",
  "url": "myspace.com/dasdf",
  "title": "MY BLOG 566",
  "year": 2023
}

###

DELETE http://localhost:3001/api/blogs/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RndXlAbWljcm9zb2Z0LmNvbSIsImlkIjoxLCJpYXQiOjE2ODEwNDQ5MDV9.3LnHqk6be8rkgj4Uhm61rITbLYdpdQNkh_fs-KkNC6U

###

PUT http://localhost:3001/api/blogs/5 HTTP/1.1
Content-Type: application/json

{
  "likes": 77
}

### users

GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "testguy@microsoft.com",
  "name": "Test Guy"
}

###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "other@microsoft.com",
  "name": "other Guy"
}


###

PUT http://localhost:3001/api/users/testguy@microsoft.de HTTP/1.1
Content-Type: application/json

{
  "username": "testguy@microsoft.com"
}

### login

POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "testguy@microsoft.com",
  "password": "secret"
}

###

POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "other@microsoft.com",
  "password": "secret"
}


###

GET http://localhost:3001/api/authors

###

POST http://localhost:3001/api/readinglists HTTP/1.1
Content-Type: application/json

{
  "blogId": 4,
  "userId": 2
}

### 

GET http://localhost:3001/api/users/2

###

PUT http://localhost:3001/api/readinglists/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RndXlAbWljcm9zb2Z0LmNvbSIsImlkIjoxLCJpYXQiOjE2ODEwNDQ5MDV9.3LnHqk6be8rkgj4Uhm61rITbLYdpdQNkh_fs-KkNC6U

{
  "read": true
}